version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mycarboot
    container_name: mycarboot-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mycarboot

  db:
    image: mysql:5.7
    container_name: mycarboot-db
    restart: unless-stopped
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql/
    networks:
      - mycarboot

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: mycarboot-phpadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /sessions
    depends_on:
      - db
    links:
      - db
    networks:
      - mycarboot

  nginx:
    image: nginx:alpine
    container_name: mycarboot-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - mycarboot

  npm:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: npm
    restart: always
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command:  npm run dev --watch
    links:
      - app
    depends_on:
      - app
    networks:
      - mycarboot

volumes:
  dbdata:
    driver: local

networks:
  mycarboot:
    driver: bridge
